server:
  port: 8082
  servlet:
    context-path: /admin

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DemoMusic;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServerDialect
  jackson:
    mapper:
      accept-case-insensitive-enums: true
    deserialization:
      fail-on-unknown-properties: false
app:
  kafka:
    topics:
      user-status: user-status-topic
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.hql.internal.ast.QueryTranslatorImpl: debug
