server:
  port: 7171
  servlet:
    context-path: /chat

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=DemoMusic;encrypt=true;trustServerCertificate=true
    username: sa
    password: 1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # JPA Configuration
  jpa:
      hibernate:
        =ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect
          format_sql: true
          use_sql_comments: true
#  flyway:
#      baseline-on-migrate: true

  # Logging Configuration
  logging:
    level:
      com.example.chatservice: DEBUG
      org.springframework.web.socket: DEBUG
      org.springframework.messaging: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"